server:
  port: 4553
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      # group:
      #  readiness:
      #   include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.laubackend.eud.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/lau/"
  application:
    name: EUD Log and Audit
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${LAU_EUD_DB_HOST:localhost}:${LAU_EUD_DB_PORT:5432}/${LAU_EUD_DB_NAME:lau_eud}${LAU_EUD_DB_CONN_OPTIONS:}
    username: ${LAU_EUD_DB_USERNAME:}
    password: ${LAU_EUD_DB_PASSWORD:}
    properties:
      charSet: UTF-8
    hikari:
      maximumPoolSize: 5
      poolName: LAUEudHikariCP
      connectionTimeout: 60000
      data-source-properties:
        socketTimeout: 60
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
  flyway:
    postgresql.transactional-lock: false
    enabled: ${LAU_FLYWAY_MIGRATE_DB:false}
    user: ${LAU_EUD_DB_ADMIN_USERNAME:}
    password: ${LAU_EUD_DB_ADMIN_PASSWORD:}
    placeholders:
      LAU_EUD_DB_PASSWORD: ${LAU_EUD_DB_PASSWORD:}

security:
  db:
    backend-encryption-key: ${LAU_EUD_ENCRYPTION_KEY:ThisIsATestKeyForEncryption}
    encryption-enabled: ${LAU_EUD_ENCRYPTION_ENABLED:Yes}

azure:
  application-insights:
    instrumentation-key: ${lau.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4502}
    secret: ${S2S_SECRET_EUD_BACKEND$:AAAAAAAAAAAAAAAA}
    microservice: lau_eud_backend
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: ${IDAM_CLIENT_NAME:lau}
    secret: ${IDAM_CLIENT_SECRET:12345678}
    username: ${IDAM_CLIENT_USERNAME:username}
    password:  ${IDAM_CLIENT_PASSWORD:special!234}
    redirect_uri: ${LAU_EUD_REDIRECT_URL:http://localhost:3451/oauth2redirect}

rd:
  professional:
    url: ${RD_PROFESSIONAL_API_URL:http://localhost:4502}


authorised.services: lau_frontend
